controller_joint_names: ['motoman_joint_s', 'motoman_joint_l', 'motoman_joint_u', 'motoman_joint_r', 'motoman_joint_b', 'motoman_joint_t']
# controller_joint_names: ['joint_s', 'joint_l', 'joint_u', 'joint_r', 'joint_b', 'joint_t']
