<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="cyl_len" value="${3.0*0.0254}"/>
  <xacro:property name="cyl_rad" value="${0.25*0.0254}"/>
  <xacro:property name="sphere_rad" value="${0.75*0.0254}"/>
  <xacro:property name="pcd" value="0.0315"/>
  <xacro:property name="offset" value="${(pcd/2.0)*sin(radians(45))}"/>

  <xacro:macro name="calibration_ee" params="prefix">

    <link name="${prefix}base_link"/>

    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 ${cyl_len/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${cyl_len}" radius="${cyl_rad}"/>
        </geometry>
        <material name="gray">
          <color rgba="0.75 0.75 0.75 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${cyl_len/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${cyl_len}" radius="${cyl_rad}"/>
        </geometry>
        <material name="gray"/>
      </collision>
    </link>

    <link name="${prefix}tool0">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${sphere_rad}"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${sphere_rad}"/>
        </geometry>
        <material name="gray"/>
      </collision>
    </link>

    <joint name="${prefix}joint_1" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <origin xyz="${offset} ${offset} 0" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}joint_2" type="fixed">
      <parent link="${prefix}link_1"/>
      <child link="${prefix}tool0"/>
      <origin xyz="0 0 ${cyl_len + sphere_rad}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>
