controller_list:
  - name: fake_calibration_ee_group_controller
    joints:
      []
  - name: fake_manipulator_controller
    joints:
      - motoman_joint_s
      - motoman_joint_l
      - motoman_joint_u
      - motoman_joint_r
      - motoman_joint_b
      - motoman_joint_t