# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  motoman_joint_b:
    has_velocity_limits: true
    max_velocity: 7.85375
    has_acceleration_limits: false
    max_acceleration: 0
  motoman_joint_l:
    has_velocity_limits: true
    max_velocity: 4.88677777777778
    has_acceleration_limits: false
    max_acceleration: 0
  motoman_joint_r:
    has_velocity_limits: true
    max_velocity: 7.85375
    has_acceleration_limits: false
    max_acceleration: 0
  motoman_joint_s:
    has_velocity_limits: true
    max_velocity: 4.71225
    has_acceleration_limits: false
    max_acceleration: 0
  motoman_joint_t:
    has_velocity_limits: true
    max_velocity: 12.566
    has_acceleration_limits: false
    max_acceleration: 0
  motoman_joint_u:
    has_velocity_limits: true
    max_velocity: 5.23583333333333
    has_acceleration_limits: false
    max_acceleration: 0